export const CATEGORIES = {
  BURGER: 'BURGER',
  DRINK: 'DRINK',
  FRIES: 'FRIES',
  TACOS: 'TACOS',
  WRAP: 'WRAP'
};

export const PROMOTION_TYPES = {
  FREE_DRINK: 'FREE_DRINK',
  MENU_DEAL: 'MENU_DEAL',
  DISCOUNT_PERCENTAGE: 'DISCOUNT_PERCENTAGE'
}; 